# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20131203212451) do

  create_table "cities", :force => true do |t|
    t.string   "name"
    t.string   "phone"
    t.integer  "state_id"
    t.datetime "created_at",         :null => false
    t.datetime "updated_at",         :null => false
    t.string   "slug"
    t.string   "btc_title"
    t.string   "btc_meta"
    t.string   "population"
    t.string   "btc_h1"
    t.string   "btc_h2"
    t.string   "btc_h3"
    t.string   "btc_h3sub1"
    t.string   "btc_h3sub1link"
    t.string   "btc_h3sub2"
    t.string   "btc_h3sub2link"
    t.string   "btc_h3sub3"
    t.string   "btc_h3sub3link"
    t.string   "btc_h3sub4"
    t.string   "btc_h3sub4link"
    t.string   "btc_h3sub5"
    t.string   "btc_h3sub5link"
    t.string   "btc_h3sub6"
    t.string   "btc_h3sub6link"
    t.string   "btc_h3sub7"
    t.string   "btc_h3sub7link"
    t.string   "btc_h3sub8"
    t.string   "btc_h3sub8link"
    t.string   "btc_h3sub9"
    t.string   "btc_h3sub9link"
    t.string   "btc_h3sub10"
    t.string   "btc_h3sub10link"
    t.string   "btc_h4"
    t.string   "btc_h4sub1"
    t.text     "btc_h4sub1section"
    t.string   "btc_h4sub2"
    t.text     "btc_h4sub2section"
    t.string   "btc_h4sub3"
    t.text     "btc_h4sub3section"
    t.string   "btc_h4sub4"
    t.text     "btc_h4sub4section"
    t.string   "btc_h4sub5"
    t.text     "btc_h4sub5section"
    t.string   "btc_h4sub6"
    t.text     "btc_h4sub6section"
    t.string   "btc_h5"
    t.text     "btc_h5section"
    t.string   "btc_h6"
    t.string   "btc_h6sub1"
    t.string   "btc_h6sub1link"
    t.text     "btc_h6sub1section"
    t.string   "btc_h6sub2"
    t.string   "btc_h6sub2link"
    t.text     "btc_h6sub2section"
    t.string   "btc_h6sub3"
    t.string   "btc_h6sub3link"
    t.text     "btc_h6sub3section"
    t.string   "btc_h6sub4"
    t.string   "btc_h6sub4link"
    t.text     "btc_h6sub4section"
    t.string   "btc_h6sub5"
    t.string   "btc_h6sub5link"
    t.text     "btc_h6sub5section"
    t.string   "btc_h6sub6"
    t.string   "btc_h6sub6link"
    t.text     "btc_h6sub6section"
    t.string   "btc_h6sub7"
    t.string   "btc_h6sub7link"
    t.text     "btc_h6sub7section"
    t.string   "btc_h6sub8"
    t.string   "btc_h6sub8link"
    t.text     "btc_h6sub8section"
    t.string   "btc_h6sub9"
    t.string   "btc_h6sub9link"
    t.text     "btc_h6sub9section"
    t.string   "btc_h6sub10"
    t.string   "btc_h6sub10link"
    t.text     "btc_h6sub10section"
    t.string   "btc_h7"
    t.text     "btc_h7section"
    t.string   "btc_h7tablel1"
    t.string   "btc_h7tabler1"
    t.string   "btc_h7tablel2"
    t.string   "btc_h7tabler2"
    t.string   "btc_h7tablel3"
    t.string   "btc_h7tabler3"
    t.string   "btc_h7tablel4"
    t.string   "btc_h7tabler4"
    t.string   "btc_h7tablel5"
    t.string   "btc_h7tabler5"
    t.string   "btc_h7tablel6"
    t.string   "btc_h7tabler6"
    t.string   "btc_h7tablel7"
    t.string   "btc_h7tabler7"
    t.string   "btc_h7tablel8"
    t.string   "btc_h7tabler8"
    t.string   "btc_h7tablel9"
    t.string   "btc_h7tabler9"
    t.string   "btc_h7tablel10"
    t.string   "btc_h7tabler10"
    t.string   "btc_h7tablel11"
    t.string   "btc_h7tabler11"
    t.string   "btc_h7tablel12"
    t.string   "btc_h7tabler12"
    t.string   "btc_h7tablel13"
    t.string   "btc_h7tabler13"
    t.string   "btc_h7tablel14"
    t.string   "btc_h7tabler14"
    t.string   "btc_h7tablel15"
    t.string   "btc_h7tabler15"
    t.string   "btc_h7tablel16"
    t.string   "btc_h7tabler16"
    t.string   "btc_h7tablel17"
    t.string   "btc_h7tabler17"
    t.string   "btc_h7tablel18"
    t.string   "btc_h7tabler18"
    t.string   "btc_h7tablel19"
    t.string   "btc_h7tabler19"
    t.string   "btc_h7tablel20"
    t.string   "btc_h7tabler20"
    t.text     "btc_h7footer"
    t.string   "std_title"
    t.string   "std_meta"
    t.string   "std_h1"
    t.string   "std_h2"
    t.string   "std_h3"
    t.string   "std_h3sub1"
    t.string   "std_h3sub1link"
    t.string   "std_h3sub2"
    t.string   "std_h3sub2link"
    t.string   "std_h3sub3"
    t.string   "std_h3sub3link"
    t.string   "std_h3sub4"
    t.string   "std_h3sub4link"
    t.string   "std_h3sub5"
    t.string   "std_h3sub5link"
    t.string   "std_h3sub6"
    t.string   "std_h3sub6link"
    t.string   "std_h3sub7"
    t.string   "std_h3sub7link"
    t.string   "std_h3sub8"
    t.string   "std_h3sub8link"
    t.string   "std_h3sub9"
    t.string   "std_h3sub9link"
    t.string   "std_h3sub10"
    t.string   "std_h3sub10link"
    t.string   "std_h4"
    t.string   "std_h4sub1"
    t.text     "std_h4sub1section"
    t.string   "std_h4sub2"
    t.text     "std_h4sub2section"
    t.string   "std_h4sub3"
    t.text     "std_h4sub3section"
    t.string   "std_h4sub4"
    t.text     "std_h4sub4section"
    t.string   "std_h4sub5"
    t.text     "std_h4sub5section"
    t.string   "std_h4sub6"
    t.text     "std_h4sub6section"
    t.string   "std_h5"
    t.text     "std_h5section"
    t.string   "std_h6"
    t.string   "std_h6sub1"
    t.string   "std_h6sub1link"
    t.text     "std_h6sub1section"
    t.string   "std_h6sub2"
    t.string   "std_h6sub2link"
    t.text     "std_h6sub2section"
    t.string   "std_h6sub3"
    t.string   "std_h6sub3link"
    t.text     "std_h6sub3section"
    t.string   "std_h6sub4"
    t.string   "std_h6sub4link"
    t.text     "std_h6sub4section"
    t.string   "std_h6sub5"
    t.string   "std_h6sub5link"
    t.text     "std_h6sub5section"
    t.string   "std_h6sub6"
    t.string   "std_h6sub6link"
    t.text     "std_h6sub6section"
    t.string   "std_h6sub7"
    t.string   "std_h6sub7link"
    t.text     "std_h6sub7section"
    t.string   "std_h6sub8"
    t.string   "std_h6sub8link"
    t.text     "std_h6sub8section"
    t.string   "std_h6sub9"
    t.string   "std_h6sub9link"
    t.text     "std_h6sub9section"
    t.string   "std_h6sub10"
    t.string   "std_h6sub10link"
    t.text     "std_h6sub10section"
    t.string   "std_h7"
    t.text     "std_h7section"
    t.string   "std_h7tablel1"
    t.string   "std_h7tabler1"
    t.string   "std_h7tablel2"
    t.string   "std_h7tabler2"
    t.string   "std_h7tablel3"
    t.string   "std_h7tabler3"
    t.string   "std_h7tablel4"
    t.string   "std_h7tabler4"
    t.string   "std_h7tablel5"
    t.string   "std_h7tabler5"
    t.string   "std_h7tablel6"
    t.string   "std_h7tabler6"
    t.string   "std_h7tablel7"
    t.string   "std_h7tabler7"
    t.string   "std_h7tablel8"
    t.string   "std_h7tabler8"
    t.string   "std_h7tablel9"
    t.string   "std_h7tabler9"
    t.string   "std_h7tablel10"
    t.string   "std_h7tabler10"
    t.string   "std_h7tablel11"
    t.string   "std_h7tabler11"
    t.string   "std_h7tablel12"
    t.string   "std_h7tabler12"
    t.string   "std_h7tablel13"
    t.string   "std_h7tabler13"
    t.string   "std_h7tablel14"
    t.string   "std_h7tabler14"
    t.string   "std_h7tablel15"
    t.string   "std_h7tabler15"
    t.string   "std_h7tablel16"
    t.string   "std_h7tabler16"
    t.string   "std_h7tablel17"
    t.string   "std_h7tabler17"
    t.string   "std_h7tablel18"
    t.string   "std_h7tabler18"
    t.string   "std_h7tablel19"
    t.string   "std_h7tabler19"
    t.string   "std_h7tablel20"
    t.string   "std_h7tabler20"
    t.text     "std_h7footer"
  end

  add_index "cities", ["slug"], :name => "index_cities_on_slug"
  add_index "cities", ["state_id"], :name => "index_cities_on_state_id"

  create_table "locations", :force => true do |t|
    t.string   "weblink"
    t.string   "name"
    t.string   "address"
    t.integer  "city_id"
    t.integer  "state_id"
    t.string   "zip"
    t.string   "hours"
    t.float    "latitude"
    t.float    "longitude"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
    t.string   "slug"
  end

  add_index "locations", ["city_id"], :name => "index_locations_on_city_id"
  add_index "locations", ["slug"], :name => "index_locations_on_slug"
  add_index "locations", ["state_id"], :name => "index_locations_on_state_id"

  create_table "roles", :force => true do |t|
    t.string   "name"
    t.integer  "resource_id"
    t.string   "resource_type"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
  end

  add_index "roles", ["name", "resource_type", "resource_id"], :name => "index_roles_on_name_and_resource_type_and_resource_id"
  add_index "roles", ["name"], :name => "index_roles_on_name"

  create_table "states", :force => true do |t|
    t.string   "name"
    t.string   "abbr"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
    t.string   "slug"
    t.string   "title"
    t.string   "meta"
    t.string   "population"
    t.string   "h1"
    t.text     "h1section"
    t.string   "h1sub1"
    t.text     "h1sub1section"
    t.string   "h1sub2"
    t.text     "h1sub2section"
    t.string   "h1sub3"
    t.text     "h1sub3section"
    t.string   "h1sub4"
    t.text     "h1sub4section"
    t.string   "h1sub5"
    t.text     "h1sub5section"
    t.string   "h1sub6"
    t.text     "h1sub6section"
    t.string   "hlocations"
    t.string   "h2"
    t.text     "h2section"
    t.string   "h3"
    t.text     "h3section"
  end

  add_index "states", ["slug"], :name => "index_states_on_slug"

  create_table "users", :force => true do |t|
    t.string   "email",                  :default => "", :null => false
    t.string   "encrypted_password",     :default => "", :null => false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          :default => 0,  :null => false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                             :null => false
    t.datetime "updated_at",                             :null => false
    t.string   "name"
  end

  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["reset_password_token"], :name => "index_users_on_reset_password_token", :unique => true

  create_table "users_roles", :id => false, :force => true do |t|
    t.integer "user_id"
    t.integer "role_id"
  end

  add_index "users_roles", ["user_id", "role_id"], :name => "index_users_roles_on_user_id_and_role_id"

end
