class AddFieldsToCities < ActiveRecord::Migration
  def change
  	add_column :cities, :btc_title,          :string
    add_column :cities, :btc_meta,           :string
    add_column :cities, :population,         :string
  	add_column :cities, :btc_h1,             :string
  	add_column :cities, :btc_h2,             :string
    add_column :cities, :btc_h3,             :string
    add_column :cities, :btc_h3sub1,         :string
    add_column :cities, :btc_h3sub1link,     :string
    add_column :cities, :btc_h3sub2,         :string
    add_column :cities, :btc_h3sub2link,     :string
    add_column :cities, :btc_h3sub3,         :string
    add_column :cities, :btc_h3sub3link,     :string
    add_column :cities, :btc_h3sub4,         :string
    add_column :cities, :btc_h3sub4link,     :string
    add_column :cities, :btc_h3sub5,         :string
    add_column :cities, :btc_h3sub5link,     :string
    add_column :cities, :btc_h3sub6,         :string
    add_column :cities, :btc_h3sub6link,     :string
    add_column :cities, :btc_h3sub7,         :string
    add_column :cities, :btc_h3sub7link,     :string
    add_column :cities, :btc_h3sub8,         :string
    add_column :cities, :btc_h3sub8link,     :string
    add_column :cities, :btc_h3sub9,         :string
    add_column :cities, :btc_h3sub9link,     :string
    add_column :cities, :btc_h3sub10,        :string
    add_column :cities, :btc_h3sub10link,    :string
    add_column :cities, :btc_h4,             :string
    add_column :cities, :btc_h4sub1,         :string
    add_column :cities, :btc_h4sub1section,  :text
    add_column :cities, :btc_h4sub2,         :string
    add_column :cities, :btc_h4sub2section,  :text
    add_column :cities, :btc_h4sub3,         :string
    add_column :cities, :btc_h4sub3section,  :text
    add_column :cities, :btc_h4sub4,         :string
    add_column :cities, :btc_h4sub4section,  :text
    add_column :cities, :btc_h4sub5,         :string
    add_column :cities, :btc_h4sub5section,  :text
    add_column :cities, :btc_h4sub6,         :string
    add_column :cities, :btc_h4sub6section,  :text
    add_column :cities, :btc_h5,             :string
    add_column :cities, :btc_h5section,      :text
    add_column :cities, :btc_h6,             :string
    add_column :cities, :btc_h6sub1,         :string
    add_column :cities, :btc_h6sub1link,     :string
    add_column :cities, :btc_h6sub1section,  :text
    add_column :cities, :btc_h6sub2,         :string
    add_column :cities, :btc_h6sub2link,     :string
    add_column :cities, :btc_h6sub2section,  :text
    add_column :cities, :btc_h6sub3,         :string
    add_column :cities, :btc_h6sub3link,     :string
    add_column :cities, :btc_h6sub3section,  :text
    add_column :cities, :btc_h6sub4,         :string
    add_column :cities, :btc_h6sub4link,     :string
    add_column :cities, :btc_h6sub4section,  :text
    add_column :cities, :btc_h6sub5,         :string
    add_column :cities, :btc_h6sub5link,     :string
    add_column :cities, :btc_h6sub5section,  :text
    add_column :cities, :btc_h6sub6,         :string
    add_column :cities, :btc_h6sub6link,     :string
    add_column :cities, :btc_h6sub6section,  :text
    add_column :cities, :btc_h6sub7,         :string
    add_column :cities, :btc_h6sub7link,     :string
    add_column :cities, :btc_h6sub7section,  :text
    add_column :cities, :btc_h6sub8,         :string
    add_column :cities, :btc_h6sub8link,     :string
    add_column :cities, :btc_h6sub8section,  :text
    add_column :cities, :btc_h6sub9,         :string
    add_column :cities, :btc_h6sub9link,     :string
    add_column :cities, :btc_h6sub9section,  :text
    add_column :cities, :btc_h6sub10,        :string
    add_column :cities, :btc_h6sub10link,    :string
    add_column :cities, :btc_h6sub10section, :text
  	add_column :cities, :btc_h7,             :string
    add_column :cities, :btc_h7section,      :text
    add_column :cities, :btc_h7tablel1,      :string
    add_column :cities, :btc_h7tabler1,      :string
    add_column :cities, :btc_h7tablel2,      :string
    add_column :cities, :btc_h7tabler2,      :string
    add_column :cities, :btc_h7tablel3,      :string
    add_column :cities, :btc_h7tabler3,      :string
    add_column :cities, :btc_h7tablel4,      :string
    add_column :cities, :btc_h7tabler4,      :string
    add_column :cities, :btc_h7tablel5,      :string
    add_column :cities, :btc_h7tabler5,      :string
    add_column :cities, :btc_h7tablel6,      :string
    add_column :cities, :btc_h7tabler6,      :string
    add_column :cities, :btc_h7tablel7,      :string
    add_column :cities, :btc_h7tabler7,      :string
    add_column :cities, :btc_h7tablel8,      :string
    add_column :cities, :btc_h7tabler8,      :string
    add_column :cities, :btc_h7tablel9,      :string
    add_column :cities, :btc_h7tabler9,      :string
    add_column :cities, :btc_h7tablel10,     :string
    add_column :cities, :btc_h7tabler10,     :string
    add_column :cities, :btc_h7tablel11,     :string
    add_column :cities, :btc_h7tabler11,     :string
    add_column :cities, :btc_h7tablel12,     :string
    add_column :cities, :btc_h7tabler12,     :string
    add_column :cities, :btc_h7tablel13,     :string
    add_column :cities, :btc_h7tabler13,     :string
    add_column :cities, :btc_h7tablel14,     :string
    add_column :cities, :btc_h7tabler14,     :string
    add_column :cities, :btc_h7tablel15,     :string
    add_column :cities, :btc_h7tabler15,     :string
    add_column :cities, :btc_h7tablel16,     :string
    add_column :cities, :btc_h7tabler16,     :string
    add_column :cities, :btc_h7tablel17,     :string
    add_column :cities, :btc_h7tabler17,     :string
    add_column :cities, :btc_h7tablel18,     :string
    add_column :cities, :btc_h7tabler18,     :string
    add_column :cities, :btc_h7tablel19,     :string
    add_column :cities, :btc_h7tabler19,     :string
    add_column :cities, :btc_h7tablel20,     :string
    add_column :cities, :btc_h7tabler20,     :string
    add_column :cities, :btc_h7footer,       :text
    add_column :cities, :std_title,          :string
    add_column :cities, :std_meta,           :string
    add_column :cities, :std_h1,             :string
    add_column :cities, :std_h2,             :string
    add_column :cities, :std_h3,             :string
    add_column :cities, :std_h3sub1,         :string
    add_column :cities, :std_h3sub1link,     :string
    add_column :cities, :std_h3sub2,         :string
    add_column :cities, :std_h3sub2link,     :string
    add_column :cities, :std_h3sub3,         :string
    add_column :cities, :std_h3sub3link,     :string
    add_column :cities, :std_h3sub4,         :string
    add_column :cities, :std_h3sub4link,     :string
    add_column :cities, :std_h3sub5,         :string
    add_column :cities, :std_h3sub5link,     :string
    add_column :cities, :std_h3sub6,         :string
    add_column :cities, :std_h3sub6link,     :string
    add_column :cities, :std_h3sub7,         :string
    add_column :cities, :std_h3sub7link,     :string
    add_column :cities, :std_h3sub8,         :string
    add_column :cities, :std_h3sub8link,     :string
    add_column :cities, :std_h3sub9,         :string
    add_column :cities, :std_h3sub9link,     :string
    add_column :cities, :std_h3sub10,        :string
    add_column :cities, :std_h3sub10link,    :string
    add_column :cities, :std_h4,             :string
    add_column :cities, :std_h4sub1,         :string
    add_column :cities, :std_h4sub1section,  :text
    add_column :cities, :std_h4sub2,         :string
    add_column :cities, :std_h4sub2section,  :text
    add_column :cities, :std_h4sub3,         :string
    add_column :cities, :std_h4sub3section,  :text
    add_column :cities, :std_h4sub4,         :string
    add_column :cities, :std_h4sub4section,  :text
    add_column :cities, :std_h4sub5,         :string
    add_column :cities, :std_h4sub5section,  :text
    add_column :cities, :std_h4sub6,         :string
    add_column :cities, :std_h4sub6section,  :text
    add_column :cities, :std_h5,             :string
    add_column :cities, :std_h5section,      :text
    add_column :cities, :std_h6,             :string
    add_column :cities, :std_h6sub1,         :string
    add_column :cities, :std_h6sub1link,     :string
    add_column :cities, :std_h6sub1section,  :text
    add_column :cities, :std_h6sub2,         :string
    add_column :cities, :std_h6sub2link,     :string
    add_column :cities, :std_h6sub2section,  :text
    add_column :cities, :std_h6sub3,         :string
    add_column :cities, :std_h6sub3link,     :string
    add_column :cities, :std_h6sub3section,  :text
    add_column :cities, :std_h6sub4,         :string
    add_column :cities, :std_h6sub4link,     :string
    add_column :cities, :std_h6sub4section,  :text
    add_column :cities, :std_h6sub5,         :string
    add_column :cities, :std_h6sub5link,     :string
    add_column :cities, :std_h6sub5section,  :text
    add_column :cities, :std_h6sub6,         :string
    add_column :cities, :std_h6sub6link,     :string
    add_column :cities, :std_h6sub6section,  :text
    add_column :cities, :std_h6sub7,         :string
    add_column :cities, :std_h6sub7link,     :string
    add_column :cities, :std_h6sub7section,  :text
    add_column :cities, :std_h6sub8,         :string
    add_column :cities, :std_h6sub8link,     :string
    add_column :cities, :std_h6sub8section,  :text
    add_column :cities, :std_h6sub9,         :string
    add_column :cities, :std_h6sub9link,     :string
    add_column :cities, :std_h6sub9section,  :text
    add_column :cities, :std_h6sub10,        :string
    add_column :cities, :std_h6sub10link,    :string
    add_column :cities, :std_h6sub10section, :text
    add_column :cities, :std_h7,             :string
    add_column :cities, :std_h7section,      :text
    add_column :cities, :std_h7tablel1,      :string
    add_column :cities, :std_h7tabler1,      :string
    add_column :cities, :std_h7tablel2,      :string
    add_column :cities, :std_h7tabler2,      :string
    add_column :cities, :std_h7tablel3,      :string
    add_column :cities, :std_h7tabler3,      :string
    add_column :cities, :std_h7tablel4,      :string
    add_column :cities, :std_h7tabler4,      :string
    add_column :cities, :std_h7tablel5,      :string
    add_column :cities, :std_h7tabler5,      :string
    add_column :cities, :std_h7tablel6,      :string
    add_column :cities, :std_h7tabler6,      :string
    add_column :cities, :std_h7tablel7,      :string
    add_column :cities, :std_h7tabler7,      :string
    add_column :cities, :std_h7tablel8,      :string
    add_column :cities, :std_h7tabler8,      :string
    add_column :cities, :std_h7tablel9,      :string
    add_column :cities, :std_h7tabler9,      :string
    add_column :cities, :std_h7tablel10,     :string
    add_column :cities, :std_h7tabler10,     :string
    add_column :cities, :std_h7tablel11,     :string
    add_column :cities, :std_h7tabler11,     :string
    add_column :cities, :std_h7tablel12,     :string
    add_column :cities, :std_h7tabler12,     :string
    add_column :cities, :std_h7tablel13,     :string
    add_column :cities, :std_h7tabler13,     :string
    add_column :cities, :std_h7tablel14,     :string
    add_column :cities, :std_h7tabler14,     :string
    add_column :cities, :std_h7tablel15,     :string
    add_column :cities, :std_h7tabler15,     :string
    add_column :cities, :std_h7tablel16,     :string
    add_column :cities, :std_h7tabler16,     :string
    add_column :cities, :std_h7tablel17,     :string
    add_column :cities, :std_h7tabler17,     :string
    add_column :cities, :std_h7tablel18,     :string
    add_column :cities, :std_h7tabler18,     :string
    add_column :cities, :std_h7tablel19,     :string
    add_column :cities, :std_h7tabler19,     :string
    add_column :cities, :std_h7tablel20,     :string
    add_column :cities, :std_h7tabler20,     :string
    add_column :cities, :std_h7footer,       :text
  end
end


